package com.example.antigravity.sdlc

import com.example.antigravity.enterprise.AuditCategory
import com.example.antigravity.enterprise.EnterpriseAuditLogger
import com.example.antigravity.model.PullRequestItem
import com.example.antigravity.studio.code.CodeStudioManager
import com.example.antigravity.studio.design.DesignTokens
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Autonomous Design-to-PR Pipeline bridging Product Design Studio, Code Studio, and GitHub.
 *
 * When a designer modifies tokens or imports them from Figma, this pipeline:
 * 1. Serializes Kotlin Jetpack Compose tokens (AppDesignTokens.kt)
 * 2. Serializes W3C Design Tokens Community Group (DTCG) standard JSON (tokens.json)
 * 3. Serializes Tailwind CSS Configuration (tailwind.tokens.js)
 * 4. Writes all artifacts directly to the active workspace directory on disk
 * 5. Dispatches an autonomous Pull Request to GitHub (or local SDLC Center) with visual release notes
 */
object DesignToPrPipeline {

    data class PipelineResult(
        val success: Boolean,
        val branchName: String,
        val pullRequest: PullRequestItem?,
        val generatedFiles: List<String>,
        val message: String
    )

    suspend fun execute(
        workspaceDir: File,
        tokens: DesignTokens,
        sourceBranchName: String = "feature/design-tokens-sync-${SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(Date())}",
        targetBranch: String = "main",
        customPrTitle: String = "chore(design): synchronize design system tokens with DTCG standard",
        customPrBody: String? = null,
        owner: String = "",
        repo: String = "",
        token: String = ""
    ): PipelineResult = withContext(Dispatchers.IO) {
        val generated = mutableListOf<String>()

        try {
            // 1. Generate & save Jetpack Compose code
            val composeCode = DesignTokens.generateComposeCode(tokens)
            val composeFile = File(workspaceDir, "AppDesignTokens.kt")
            val composeOk = CodeStudioManager.saveFileContent(composeFile, composeCode)
            if (composeOk) generated.add("AppDesignTokens.kt")

            // 2. Generate & save W3C DTCG Standard Tokens JSON
            val dtcgJson = tokens.generateW3cDtcgJson()
            val dtcgFile = File(workspaceDir, "tokens.json")
            val dtcgOk = CodeStudioManager.saveFileContent(dtcgFile, dtcgJson)
            if (dtcgOk) generated.add("tokens.json")

            // 3. Generate & save Tailwind Config
            val tailwindJs = tokens.generateTailwindConfig()
            val tailwindFile = File(workspaceDir, "tailwind.tokens.js")
            val tailwindOk = CodeStudioManager.saveFileContent(tailwindFile, tailwindJs)
            if (tailwindOk) generated.add("tailwind.tokens.js")

            // 4. Generate & save CSS Custom Properties
            val cssProps = tokens.generateCssVariables()
            val cssFile = File(workspaceDir, "design-tokens.css")
            val cssOk = CodeStudioManager.saveFileContent(cssFile, cssProps)
            if (cssOk) generated.add("design-tokens.css")

            // 5. Construct PR markdown body with visual specs
            val prBody = customPrBody ?: """
                ## 🎨 Automated Design System Tokens Synchronization
                
                Synchronized directly from **Antigravity Product Design Studio** with W3C DTCG compliance.
                
                ### 📋 Synchronized Artifacts
                - `AppDesignTokens.kt`: Native Jetpack Compose design tokens
                - `tokens.json`: W3C Design Tokens Community Group (DTCG) Standard format
                - `tailwind.tokens.js`: Tailwind CSS theme configuration
                - `design-tokens.css`: CSS Custom Properties (CSS variables)
                
                ### 🎯 Key Design System Values
                | Token | Value | Sample |
                |---|---|---|
                | **Primary Color** | `${tokens.primaryColorHex}` | <span style="background-color: ${tokens.primaryColorHex}; padding: 2px 12px; border-radius: 4px; border: 1px solid #ccc;">&nbsp;</span> |
                | **Secondary Color** | `${tokens.secondaryColorHex}` | <span style="background-color: ${tokens.secondaryColorHex}; padding: 2px 12px; border-radius: 4px; border: 1px solid #ccc;">&nbsp;</span> |
                | **Corner Radius** | `${tokens.cornerRadiusDp}dp` | Rounded components |
                | **Elevation** | `${tokens.elevationDp}dp` | Layer surface depth |
                | **Header Font Size** | `${tokens.headerFontSizeSp}sp` | Typography scale factor |
                | **Body Font Size** | `${tokens.bodyFontSizeSp}sp` | Typography scale factor |
                
                ---
                *Automated delivery generated by Antigravity SDLC Pipeline Engine.*
            """.trimIndent()

            // 6. Create PR via SdlcManager (first pushing the branch with the generated files)
            val branchFiles: List<Pair<String, String>> = generated.mapNotNull { fileName ->
                val content = runCatching { File(workspaceDir, fileName).readText() }.getOrNull()
                if (content != null) fileName to content else null
            }
            val prResult = SdlcManager.createPullRequestWithBranch(
                title = customPrTitle,
                sourceBranch = sourceBranchName,
                targetBranch = targetBranch,
                body = prBody,
                files = branchFiles,
                branchCommitMessage = "chore(design): synchronize design system tokens [skip ci]",
                token = token,
                owner = owner,
                repo = repo
            )

            if (prResult.isSuccess) {
                val pr = prResult.getOrNull()
                EnterpriseAuditLogger.log(
                    category = AuditCategory.SDLC_OPERATION,
                    action = "DESIGN_TO_PR_SUCCESS",
                    details = "Dispatched Design-to-PR pipeline: ${generated.joinToString(", ")} -> PR #${pr?.number}"
                )
                PipelineResult(
                    success = true,
                    branchName = sourceBranchName,
                    pullRequest = pr,
                    generatedFiles = generated,
                    message = "Successfully created PR #${pr?.number ?: "local"} from branch '$sourceBranchName'!"
                )
            } else {
                val errorMsg = prResult.exceptionOrNull()?.message ?: "Unknown PR creation failure"
                EnterpriseAuditLogger.log(
                    category = AuditCategory.SDLC_OPERATION,
                    action = "DESIGN_TO_PR_PR_FAILED",
                    details = "Tokens written to disk (${generated.joinToString()}), but PR dispatch failed: $errorMsg"
                )
                PipelineResult(
                    success = false,
                    branchName = sourceBranchName,
                    pullRequest = null,
                    generatedFiles = generated,
                    message = "Files saved to workspace, but PR dispatch encountered: $errorMsg"
                )
            }
        } catch (e: Exception) {
            EnterpriseAuditLogger.log(
                category = AuditCategory.SDLC_OPERATION,
                action = "DESIGN_TO_PR_EXCEPTION",
                details = "Error running Design-to-PR pipeline: ${e.message}"
            )
            PipelineResult(
                success = false,
                branchName = sourceBranchName,
                pullRequest = null,
                generatedFiles = generated,
                message = "Pipeline error: ${e.message}"
            )
        }
    }
}
